### ISSUE TITLE
e..com.cn

### ISSUE THREAD

**Issue by w3bservice** [hezhijie0327/AdFilter#2]
unbound-checkconf[31353]: [1632268132] unbound-checkconf[31353:0] error: cannot parse name e..com.cn
unbound-checkconf[31353]: [1632268132] unbound-checkconf[31353:0] error: bad zone name e..com.cn always_nxdomain
unbound-checkconf[31353]: [1632268132] unbound-checkconf[31353:0] fatal error: failed local-zone, local-data configuration

**Comment by hezhijie0327** [comment]
Fixed. 24de38c
